version: '3.3'
services:
  e2e-test:
    container_name: e2e-test
    build:
      context: .
      dockerfile: Dockerfile-e2e-test
    ports:
      - "4000:4000"
      - "4001:4001"
      - "5105:5105"
    depends_on:
      - spp-platform
      - skywalking-oap
    links:
      - spp-platform
      - skywalking-oap
  spp-platform:
    image: sourceplusplus/spp-platform:latest
    container_name: spp-platform
    hostname: spp-platform
    ports:
      - "5445:5445"
      - "5450:5450"
      - "5455:5455"
      - "5107:5107"
    environment:
      - SPP_LOGGING_LEVEL=trace
      - SPP_OAP_HOST=skywalking-oap
      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5107
    volumes:
      - ./config/spp-platform.crt:/opt/sourceplusplus/config/spp-platform.crt
      - ./config/spp-platform.key:/opt/sourceplusplus/config/spp-platform.key
  skywalking-oap:
    image: sourceplusplus/spp-oap-server:latest
    container_name: skywalking-oap
    hostname: skywalking-oap
    ports:
      - "11800:11800"
    environment:
      - SPP_PLATFORM_HOST=spp-platform
      - SPP_PLATFORM_PORT=5460
      - SPP_PLATFORM_CERTIFICATE_FILE=/skywalking/spp-platform.crt
      - SW_CORE_GRPC_SSL_ENABLED=true
      - SW_CORE_GRPC_SSL_KEY_PATH=/skywalking/spp-platform.key
      - SW_CORE_GRPC_SSL_CERT_CHAIN_PATH=/skywalking/spp-platform.crt
      - SW_CORE_GRPC_SSL_TRUSTED_CA_PATH=/skywalking/spp-platform.crt
      - SW_RECEIVER_GRPC_SSL_ENABLED=true
      - SW_RECEIVER_GRPC_SSL_KEY_PATH=/skywalking/spp-platform.key
      - SW_RECEIVER_GRPC_SSL_CERT_CHAIN_PATH=/skywalking/spp-platform.crt
    volumes:
      - ./config/spp-platform.crt:/skywalking/spp-platform.crt
      - ./config/spp-platform.key:/skywalking/spp-platform.key
